export const SET_COMMENTS = `SET_COMMENTS`;

export const GET_COMMENTS = `GET_COMMENTS`;

export const CREATE_COMMENT = `CREATE_COMMENT`;

export const UPDATE_COMMENT = `UPDATE_COMMENT`;

export const DELETE_COMMENT = `DELETE_COMMENT`;

export const COMMENT_ACTIONS = new Set([
  SET_COMMENTS,
  UPDATE_COMMENT,
  DELETE_COMMENT,
  GET_COMMENTS,
  CREATE_COMMENT,
]);
